import os
import sys

print(os)
print(sys)

a = "python"

b = "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"

frutas = [
    "pera",
    "maçã",
    "laranja",
    "uva",
    "melão",
    "morango",
    "abacate",
    "banana",
    "carambola",
    "pessego",
    "tamara",
    "melancia",
]

carros = ["ferrari", "brasilia", "gol", "up"]

#------------------------------------------------------------------------------------#

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.11"

#------------------------------------------------------------------------------------#

{
    "_meta": {
        "hash": {
            "sha256": "ed6d5d614626ae28e274e453164affb26694755170ccab3aa5866f093d51d3e4"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.11"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

#------------------------------------------------------------------------------------#
# This file is automatically @generated by Poetry 1.4.2 and should not be changed by hand.
package = []

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "81b2fa642d7f2d1219cf80112ace12d689d053d81be7f7addb98144d56fc0fb2"
[tool.poetry]
name = "01 - ambiente virtual"
version = "0.1.0"
description = ""
authors = ["Guilherme Carvalho <gui.ifsp11@gmail.com>"]
readme = "README.md"
packages = [{include = "01 _ ambiente virtual"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"